apiVersion: v2
name: janus
description: Atomic multi-resource changes for Kubernetes (Saga pattern)
type: application
version: 0.2.3
appVersion: "v0.2.3"
home: https://github.com/aalpar/janus
sources:
  - https://github.com/aalpar/janus
maintainers:
  - name: aalpar
    url: https://github.com/aalpar
keywords:
  - kubernetes
  - operator
  - saga
  - transactions
  - rollback
